# Generated by Django 5.2 on 2025-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='feedback_images/')),
            ],
        ),
    ]
