# Generated by Django 5.2 on 2025-04-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
        ('store', '0005_alter_category_image'),
    ]

    operations = [
    ]
