# Generated by Django 5.2 on 2025-05-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_0003_order_0005_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
